### ISSUE TITLE
Posible error en la visualización de respuestas

### ISSUE THREAD

**Issue by isorna** [KairosDS/KuestionsMeteor#10]
Mirar en el admin las respuestas de js2 y friki de EduardoLQ, las preguntas y respuestas salen como en columnas diferentes, algunas sin orden ni concierto.

**Comment by manufosela** [comment]
Solucionado.
Si encontramos resultados incongruentes en algun usuario (45 de 34 por ejemplo), debemos dar al boton RECALC dos veces. La primera recalcula el numero de preguntas, el segundo clic recalcula el numero de respuestas correctas.
